##

version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_FIREBASE_CONFIG=${REACT_APP_FIREBASE_CONFIG}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-adminsdk.json
    volumes:
      - ./backend/firebase-adminsdk.json:/app/firebase-adminsdk.json